env:
  browser: true
  es2021: true
extends: 
-airbnb
-prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  prettier/prettier:
    - error
    - semi: true
    - singleQuote: true
    - trailingComma: all
    - bracketSpacing: false